import { Product, Category, Banner } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Health & Personal', slug: 'health-personal', image: '/images/categories/health.jpg' },
  { id: '2', name: 'Grocery', slug: 'grocery', image: '/images/categories/grocery.jpg' },
  { id: '3', name: 'Beauty', slug: 'beauty', image: '/images/categories/beauty.jpg' },
  { id: '4', name: 'Kitchen', slug: 'kitchen', image: '/images/categories/kitchen.jpg' },
  { id: '5', name: 'Home', slug: 'home', image: '/images/categories/home.jpg' },
  { id: '6', name: 'Office', slug: 'office', image: '/images/categories/office.jpg' },
  { id: '7', name: 'Fashion', slug: 'fashion', image: '/images/categories/fashion.jpg' },
  { id: '8', name: 'Baby', slug: 'baby', image: '/images/categories/baby.jpg' },
  { id: '9', name: 'Art & Craft', slug: 'art-craft', image: '/images/categories/art.jpg' },
];

export const banners: Banner[] = [
  {
    id: '1',
    title: 'Embrace Traditional Kitchen Tools',
    subtitle: 'Brass | Copper | Stainless Steel',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&h=400&fit=crop',
    cta: 'Buy now',
    link: '/products/kitchen',
  },
  {
    id: '2',
    title: 'Herbal Medicine | 30% Off',
    subtitle: 'Natural & Organic Products',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=1200&h=400&fit=crop',
    cta: 'Shop Now',
    link: '/products/health-personal',
  },
  {
    id: '3',
    title: 'Immunity Boosters | 30% Off',
    subtitle: 'Boost Your Health Naturally',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&h=400&fit=crop',
    cta: 'Shop Now',
    link: '/products/health-personal',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Traditional Copper Cookware Set',
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop',
    category: 'kitchen',
    description: 'Premium copper cookware set for traditional cooking',
    rating: 4.5,
    reviews: 128,
    inStock: true,
  },
  {
    id: '2',
    name: 'Organic Herbal Supplement Pack',
    price: 29.99,
    originalPrice: 42.99,
    discount: 30,
    image: 'https://images.unsplash.com/photo-1550572017-4814c5c6e0e2?w=400&h=400&fit=crop',
    category: 'health-personal',
    description: 'Natural herbal supplements for daily wellness',
    rating: 4.8,
    reviews: 256,
    inStock: true,
  },
  {
    id: '3',
    name: 'Immunity Booster Vitamins',
    price: 24.99,
    originalPrice: 35.99,
    discount: 30,
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&h=400&fit=crop',
    category: 'health-personal',
    description: 'Boost your immune system with natural ingredients',
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '4',
    name: 'Natural Face Care Kit',
    price: 39.99,
    originalPrice: 59.99,
    discount: 33,
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=400&h=400&fit=crop',
    category: 'beauty',
    description: 'Complete natural skincare routine',
    rating: 4.7,
    reviews: 342,
    inStock: true,
  },
  {
    id: '5',
    name: 'Luxury Beauty Collection',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    category: 'beauty',
    description: 'Premium beauty products for radiant skin',
    rating: 4.9,
    reviews: 421,
    inStock: true,
  },
  {
    id: '6',
    name: 'Handmade Puppet Collection',
    price: 19.99,
    originalPrice: 26.99,
    discount: 25,
    image: 'https://images.unsplash.com/photo-1587912781340-f87ac021a9cf?w=400&h=400&fit=crop',
    category: 'art-craft',
    description: 'Traditional handmade puppets',
    rating: 4.4,
    reviews: 87,
    inStock: true,
  },
  {
    id: '7',
    name: 'Eco-Friendly Jute Bags',
    price: 14.99,
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&h=400&fit=crop',
    category: 'home',
    description: 'Sustainable living essentials',
    rating: 4.3,
    reviews: 156,
    inStock: true,
  },
  {
    id: '8',
    name: 'Organic Spice Collection',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1596040033229-a0b27c5c9bb3?w=400&h=400&fit=crop',
    category: 'grocery',
    description: 'Premium organic spices from India',
    rating: 4.8,
    reviews: 298,
    inStock: true,
  },
];

export const promotionalSections = [
  {
    id: 'herbal',
    title: 'Herbal medicine | 30% Off',
    category: 'health-personal',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=400&fit=crop',
    subtitle: 'Herbal Supplement',
    price: 'Up to 30',
  },
  {
    id: 'immunity',
    title: 'Immunity Boosters | 30% Off',
    category: 'health-personal',
    image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=400&fit=crop',
  },
  {
    id: 'herbs',
    title: 'Herbs from the Deep Forests',
    category: 'health-personal',
    image: 'https://images.unsplash.com/photo-1508161773455-3ada8ed2bbec?w=600&h=400&fit=crop',
    subtitle: 'Raw Herbs',
    price: 'Up to 30',
  },
  {
    id: 'embrace',
    title: 'Embrace your Health',
    category: 'health-personal',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=400&fit=crop',
  },
  {
    id: 'bath',
    title: 'Bath & Body',
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=400&fit=crop',
    subtitle: 'Bath & Body',
    price: 'Up to 30',
  },
  {
    id: 'cruelty-free',
    title: 'Cruelty free Beauty',
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=600&h=400&fit=crop',
  },
  {
    id: 'luxury',
    title: 'Luxury Beauty',
    category: 'beauty',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=400&fit=crop',
    subtitle: 'Luxury Beauty',
    price: 'Up to 30',
  },
  {
    id: 'feel-good',
    title: 'Feel Good | 40% Off',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&h=400&fit=crop',
  },
];
