import { Product, Category, Banner, PromoBanner } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Dairy & Milk",
    slug: "cake-milk",
    image:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=120&h=120&fit=crop",
    icon: "🥛",
    itemCount: 11,
  },
  {
    id: "2",
    name: "Organic Produce",
    slug: "organic",
    image:
      "https://images.unsplash.com/photo-1585059895524-72359e06133a?w=120&h=120&fit=crop",
    icon: "🥝",
    itemCount: 6,
  },
  {
    id: "3",
    name: "Fresh Fruits",
    slug: "fruits",
    image:
      "https://images.unsplash.com/photo-1629828874514-c1e5103f2100?w=120&h=120&fit=crop",
    icon: "🍑",
    itemCount: 16,
  },
  {
    id: "4",
    name: "Spices & Herbs",
    slug: "spices",
    image:
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=120&h=120&fit=crop",
    icon: "🌶️",
    itemCount: 10,
  },
  {
    id: "5",
    name: "Snacks & Bites",
    slug: "snacks",
    image:
      "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=120&h=120&fit=crop",
    icon: "🍿",
    itemCount: 11,
  },
  {
    id: "6",
    name: "Vegetables",
    slug: "vegetable",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=120&h=120&fit=crop",
    icon: "🥬",
    itemCount: 6,
  },
  {
    id: "7",
    name: "Grains & Rice",
    slug: "grains",
    image:
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=120&h=120&fit=crop",
    icon: "🌾",
    itemCount: 10,
  },
  {
    id: "8",
    name: "Pulses & Lentils",
    slug: "pulses",
    image:
      "https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=120&h=120&fit=crop",
    icon: "🫘",
    itemCount: 10,
  },
  {
    id: "9",
    name: "Oils & Ghee",
    slug: "oils",
    image:
      "https://images.unsplash.com/photo-1474979266404-7f28235f7e2e?w=120&h=120&fit=crop",
    icon: "🫒",
    itemCount: 8,
  },
  {
    id: "10",
    name: "Beverages",
    slug: "beverages",
    image:
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=120&h=120&fit=crop",
    icon: "☕",
    itemCount: 11,
  },
];

export const banners: Banner[] = [
  {
    id: "1",
    title: "Premium Agri Products Direct to Your Store",
    subtitle:
      "Smart sourcing from verified farms. Bulk supply for UK retailers with doorstep delivery.",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&h=500&fit=crop",
    cta: "Explore Products",
    link: "/products/vegetable",
  },
  {
    id: "2",
    title: "Farm Fresh. Globally Sourced. UK Delivered.",
    subtitle:
      "From farm to shelf — premium fruits, vegetables, spices & staples imported for UK retailers.",
    image:
      "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200&h=500&fit=crop",
    cta: "Browse Catalogue",
    link: "/products/fruits",
  },
  {
    id: "3",
    title: "Smart Logistics. Faster Supply Chain.",
    subtitle:
      "Reliable B2B supply with real-time tracking and competitive wholesale pricing.",
    image:
      "https://images.unsplash.com/photo-1506484381205-f7945b68db56?w=1200&h=500&fit=crop",
    cta: "Get Started",
    link: "/products/organic",
  },
];

export const promoBanners: PromoBanner[] = [
  {
    id: "1",
    label: "Save",
    value: "£29",
    description: "Bulk order discounts on all grocery & frozen items.",
    bgColor: "bg-orange-50",
    textColor: "text-orange-600",
  },
  {
    id: "2",
    label: "Discount",
    value: "30%",
    description: "First-order discount for new retail partners.",
    bgColor: "bg-red-50",
    textColor: "text-red-600",
  },
  {
    id: "3",
    label: "Up to",
    value: "50%",
    description: "Seasonal clearance on imported produce.",
    bgColor: "bg-blue-50",
    textColor: "text-blue-600",
  },
  {
    id: "4",
    label: "Free",
    value: "SHIP",
    description: "Free delivery on orders over £500.",
    bgColor: "bg-green-50",
    textColor: "text-green-600",
  },
];

export const promoCards = [
  {
    id: "1",
    title: "Everyday Fresh & Clean Produce for Your Shelves",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=400&fit=crop",
    bgColor: "bg-green-50",
    link: "/products/vegetable",
  },
  {
    id: "2",
    title: "Premium Breakfast & Snack Lines for Retailers",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
    bgColor: "bg-yellow-50",
    link: "/products/snacks",
  },
  {
    id: "3",
    title: "Certified Organic Products Sourced Globally",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop",
    bgColor: "bg-purple-50",
    link: "/products/organic",
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Seeds of Change Organic Red Rice",
    price: 28.85,
    originalPrice: 32.0,
    discount: 13,
    image:
      "https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?w=400&h=400&fit=crop",
    category: "grains",
    categoryLabel: "Grains & Rice",
    description: "Premium organic red rice, sourced from verified farms",
    weight: "500 gm",
    rating: 2,
    reviews: 1,
    vendor: "Punjab Agro",
    badge: "sale",
    inStock: true,
  },
  {
    id: "2",
    name: "All Natural Free-Range Chicken Meatballs",
    price: 23.0,
    originalPrice: 122.0,
    discount: 66,
    image:
      "https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop",
    category: "chicken-meat",
    categoryLabel: "Fresh Meat",
    description: "All natural free-range chicken meatballs",
    weight: "1 kg",
    rating: 5,
    reviews: 3,
    vendor: "FarmLink Direct",
    badge: "hot",
    inStock: true,
  },
  {
    id: "3",
    name: "Angie's Sweet & Salty Kettle Corn",
    price: 48.85,
    originalPrice: 52.0,
    discount: 8,
    image:
      "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&h=400&fit=crop",
    category: "snacks",
    categoryLabel: "Snacks & Bites",
    description: "Sweet and salty kettle corn — retail pack",
    weight: "350 gm",
    rating: 4,
    reviews: 1,
    vendor: "Harvest Fields",
    badge: "new",
    inStock: true,
  },
  {
    id: "4",
    name: "Foster Farms Takeout Crispy Classic",
    price: 17.85,
    originalPrice: 19.0,
    discount: 0,
    image:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop",
    category: "snacks",
    categoryLabel: "Snacks & Bites",
    description: "Crispy classic wings — bulk supply",
    weight: "350 gm",
    rating: 0,
    reviews: 0,
    vendor: "Harvest Fields",
    badge: "out",
    inStock: false,
  },
  {
    id: "5",
    name: "Blue Almonds Lightly Salted Vegetables",
    price: 23.85,
    originalPrice: 25.0,
    discount: 2,
    image:
      "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=400&h=400&fit=crop",
    category: "vegetable",
    categoryLabel: "Fresh Vegetables",
    description: "Lightly salted mixed vegetables — farm sourced",
    weight: "400 gm",
    rating: 4,
    reviews: 2,
    vendor: "Green Valley Exports",
    inStock: true,
  },
  {
    id: "6",
    name: "Organic Cage-Free Grade A Large Brown Eggs",
    price: 14.29,
    originalPrice: 18.99,
    discount: 25,
    image:
      "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=400&fit=crop",
    category: "organic",
    categoryLabel: "Organic Produce",
    description: "Certified organic free-range eggs",
    weight: "12 pcs",
    rating: 5,
    reviews: 7,
    vendor: "Punjab Agro",
    badge: "hot",
    inStock: true,
  },
  {
    id: "7",
    name: "Gortons Beer Battered Fish Fillets",
    price: 18.29,
    originalPrice: 24.99,
    discount: 27,
    image:
      "https://images.unsplash.com/photo-1534483509719-3feaee7c30da?w=400&h=400&fit=crop",
    category: "chicken-meat",
    categoryLabel: "Fresh Seafood",
    description: "Beer battered crispy fish fillets — wholesale",
    weight: "600 gm",
    rating: 4,
    reviews: 5,
    vendor: "FarmLink Direct",
    badge: "sale",
    inStock: true,
  },
  {
    id: "8",
    name: "Haagen Caramel Cone Ice Cream",
    price: 20.29,
    originalPrice: 26.99,
    discount: 8,
    image:
      "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&h=400&fit=crop",
    category: "cake-milk",
    categoryLabel: "Dairy & Milk",
    description: "Premium caramel cone ice cream",
    weight: "500 ml",
    rating: 3,
    reviews: 4,
    vendor: "Harvest Fields",
    inStock: true,
  },
  {
    id: "9",
    name: "Encore Seafoods Stuffed Mushrooms",
    price: 8.29,
    originalPrice: 12.99,
    discount: 6,
    image:
      "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=400&fit=crop",
    category: "chicken-meat",
    categoryLabel: "Fresh Seafood",
    description: "Gourmet stuffed mushrooms with seafood",
    weight: "350 gm",
    rating: 4,
    reviews: 2,
    vendor: "FarmLink Direct",
    badge: "sale",
    inStock: true,
  },
  {
    id: "10",
    name: "Canada Dry Ginger Ale - 2L",
    price: 15.29,
    originalPrice: 19.99,
    discount: 2,
    image:
      "https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=400&h=400&fit=crop",
    category: "beverages",
    categoryLabel: "Beverages",
    description: "Canada Dry ginger ale 2L — case supply",
    weight: "2 Ltr",
    rating: 3,
    reviews: 3,
    vendor: "Harvest Fields",
    inStock: true,
  },
  {
    id: "11",
    name: "Italian Avocado Premium",
    price: 12.29,
    originalPrice: 15.99,
    discount: 23,
    image:
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop",
    category: "fruits",
    categoryLabel: "Fresh Fruits",
    description: "Premium Italian avocados, perfectly ripe",
    weight: "250 gm",
    rating: 5,
    reviews: 12,
    vendor: "Green Valley Exports",
    badge: "hot",
    inStock: true,
  },
  {
    id: "12",
    name: "Fresh Local Carrots Organic",
    price: 19.29,
    originalPrice: 24.99,
    discount: 23,
    image:
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop",
    category: "vegetable",
    categoryLabel: "Vegetables",
    description: "Fresh local carrots from organic farms",
    weight: "1 kg",
    rating: 4,
    reviews: 8,
    vendor: "Punjab Agro",
    inStock: true,
  },
  {
    id: "13",
    name: "Lays Chips Bacon Flavor",
    price: 21.29,
    originalPrice: 27.99,
    discount: 24,
    image:
      "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop",
    category: "snacks",
    categoryLabel: "Snacks",
    description: "Crispy bacon flavored potato chips — retail box",
    weight: "250 gm",
    rating: 4,
    reviews: 15,
    vendor: "Harvest Fields",
    badge: "sale",
    inStock: true,
  },
  {
    id: "14",
    name: "Fresh Whole Milk Farm",
    price: 6.29,
    originalPrice: 8.99,
    discount: 30,
    image:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop",
    category: "cake-milk",
    categoryLabel: "Dairy & Milk",
    description: "Farm fresh whole milk, pasteurized",
    weight: "1 Ltr",
    rating: 5,
    reviews: 23,
    vendor: "FarmLink Direct",
    badge: "hot",
    inStock: true,
  },
  {
    id: "15",
    name: "Extra Virgin Olive Oil Cold Press",
    price: 24.29,
    originalPrice: 32.99,
    discount: 26,
    image:
      "https://images.unsplash.com/photo-1474979266404-7f28235f7e2e?w=400&h=400&fit=crop",
    category: "oils",
    categoryLabel: "Oils & Ghee",
    description: "Premium extra virgin olive oil, cold pressed",
    weight: "500 ml",
    rating: 5,
    reviews: 19,
    vendor: "Green Valley Exports",
    badge: "new",
    inStock: true,
  },
  {
    id: "16",
    name: "Fresh Strawberries Pack",
    price: 11.29,
    originalPrice: 15.99,
    discount: 29,
    image:
      "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop",
    category: "fruits",
    categoryLabel: "Fresh Fruits",
    description: "Sweet and juicy fresh strawberries",
    weight: "250 gm",
    rating: 4,
    reviews: 11,
    vendor: "Punjab Agro",
    badge: "sale",
    inStock: true,
  },
  {
    id: "17",
    name: "Organic Frozen Vegetable Mix",
    price: 14.29,
    originalPrice: 18.99,
    discount: 25,
    image:
      "https://images.unsplash.com/photo-1615485500710-aa71060943f4?w=400&h=400&fit=crop",
    category: "vegetable",
    categoryLabel: "Vegetables",
    description: "Certified organic frozen vegetables mix",
    weight: "500 gm",
    rating: 3,
    reviews: 6,
    vendor: "Green Valley Exports",
    inStock: true,
  },
  {
    id: "18",
    name: "Premium Beef Mixed Cuts",
    price: 16.29,
    originalPrice: 22.99,
    discount: 29,
    image:
      "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400&h=400&fit=crop",
    category: "chicken-meat",
    categoryLabel: "Fresh Meat",
    description: "Premium quality beef cuts — wholesale",
    weight: "1 kg",
    rating: 4,
    reviews: 14,
    vendor: "FarmLink Direct",
    badge: "hot",
    inStock: true,
  },
  {
    id: "19",
    name: "Bhani Complete Vanilla Ice Cream",
    price: 9.99,
    originalPrice: 14.5,
    discount: 2,
    image:
      "https://images.unsplash.com/photo-1570197571499-166b36435e9f?w=400&h=400&fit=crop",
    category: "cake-milk",
    categoryLabel: "Dairy & Milk",
    description: "Creamy vanilla ice cream — case of 6",
    weight: "1 Ltr",
    rating: 4,
    reviews: 9,
    vendor: "Harvest Fields",
    inStock: true,
  },
  {
    id: "20",
    name: "Fresh Cucumber Local Organic",
    price: 4.29,
    originalPrice: 5.99,
    discount: 28,
    image:
      "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=400&fit=crop",
    category: "vegetable",
    categoryLabel: "Vegetables",
    description: "Fresh local cucumbers, crisp and green",
    weight: "500 gm",
    rating: 4,
    reviews: 3,
    vendor: "Punjab Agro",
    inStock: true,
  },
];

export const promotionalSections = [
  {
    id: "fresh-veggies",
    title: "Fresh Vegetables | 20% Off",
    category: "vegetable",
    image:
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&h=400&fit=crop",
    subtitle: "Farm Fresh",
    price: "Up to 20",
  },
  {
    id: "organic",
    title: "Organic Products | 25% Off",
    category: "organic",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop",
  },
  {
    id: "frozen",
    title: "Frozen Food Collection",
    category: "snacks",
    image:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=600&h=400&fit=crop",
    subtitle: "Ready to Cook",
    price: "Up to 30",
  },
  {
    id: "dairy",
    title: "Dairy Products",
    category: "cake-milk",
    image:
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&h=400&fit=crop",
  },
];
